#! /bin/bash
#
# This Cygwin Bash script allows one to run MX's 'mxmotor' program with
# options and save the output to a log file using /usr/bin/script.
#

if [ $# == 0 ]; then
    echo "Usage: run_mxmotor 'logfile_name' [ mxmotor_options ... ]"
    exit 1
fi

set -x

/usr/bin/script -c "/cygdrive/c/WINDOWS/system32/cmd /C C:\\\\opt\\\\mx\\\\bin\\\\mxmotor $2 $3 $4 $5 $6 $7 $8 $9" -f $1

exit 0

