#! /bin/bash
#
# This Cygwin Bash script allows one to run MX's 'motor_as_server' program with
# options and save the output to a log file using /usr/bin/script.
#

if [ $# == 0 ]; then
    echo "Usage: run_motor_as_server 'logfile_name' [ motor_as_server_options ... ]"
    exit 1
fi

set -x

/usr/bin/script -c "/cygdrive/c/WINDOWS/system32/cmd /C C:\\\\opt\\\\mx\\\\sbin\\\\motor_as_server $2 $3 $4 $5 $6 $7 $8 $9" -f $1

exit 0

