#! /bin/sh

if [ x${MXDIR} = x ]; then
	MXDIR=/opt/mx
fi

export MXDIR

if [ x${LD_LIBRARY_PATH} = x ]; then
	LD_LIBRARY_PATH=../../libMx
else
	LD_LIBRARY_PATH=../../libMx:${LD_LIBRARY_PATH}
fi

export LD_LIBRARY_PATH

../../motor/mxmotor -F ${MXDIR}/etc/mxmotor.dat -s $HOME/mxscan.dat $*

