#! /bin/sh
#
# Name:    mxsave
#
# Purpose: This script saves the current values of a user-specified set of
#          runtime database parameters to a file.  Parameters from both MX
#          and EPICS servers are supported.  See the man page mxupdate.dat(5)
#          for the format of the file used to specify the list of parameters.
#
# Author:  William Lavender
#
#--------------------------------------------------------------------------
#
# Copyright 2007 Illinois Institute of Technology
#
# See the file "LICENSE" for information on usage and redistribution
# of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#

if [ x$MXDIR = x ]; then
	MXDIR=/opt/mx
fi

MXUPDATE=${MXDIR}/sbin/mxupdate

if [ $# != 2 ]; then
	echo ""
	echo "Usage: $0  parameter_list_filename  parameter_values_filename"
	echo ""
	exit 1
fi

exec ${MXUPDATE} -s $1 $2

