#! /bin/sh

set -x

if [ x$MXDIR = x ]; then
	MXDIR=/opt/mx
fi

MXAUTOSAVE=${MXDIR}/sbin/mxautosave

if [ x$LD_LIBRARY_PATH = x ]; then
	LD_LIBRARY_PATH=${MXDIR}/lib
else
	LD_LIBRARY_PATH="${MXDIR}/lib:${LD_LIBRARY_PATH}"
fi

if [ x$DYLD_LIBRARY_PATH = x ]; then
	DYLD_LIBRARY_PATH=${MXDIR}/lib
else
	DYLD_LIBRARY_PATH="${MXDIR}/lib:${DYLD_LIBRARY_PATH}"
fi

if [ x$SHLIB_PATH = x ]; then
	SHLIB_PATH=${MXDIR}/lib
else
	SHLIB_PATH="${MXDIR}/lib:${SHLIB_PATH}"
fi

export MXDIR LD_LIBRARY_PATH DYLD_LIBRARY_PATH SHLIB_PATH

#----

OS=`uname -s`

if [ $OS = "Linux" ]; then
	SESSION="setsid"
else
	SESSION="nohup"
fi

#----

#
# If mxautosave.dat exists and has a non-zero size, then we start mxautosave.
#

if [ -s ${MXDIR}/etc/mxautosave.dat ]; then

	if [ -x $MXAUTOSAVE ]; then
		cd ${MXDIR}/run

		if [ x${MX_NO_DETACH} != x ]; then
			exec $MXAUTOSAVE $* \
				-O ${MXDIR}/run/mxautosave.pid \
				${MXDIR}/etc/mxautosave.dat \
				${MXDIR}/state/mxsave.1 \
				${MXDIR}/state/mxsave.2
		else
			( ${SESSION} $MXAUTOSAVE $* \
				-O ${MXDIR}/run/mxautosave.pid \
				${MXDIR}/etc/mxautosave.dat \
				${MXDIR}/state/mxsave.1 \
				${MXDIR}/state/mxsave.2 \
			    < /dev/null >> ${MXDIR}/log/mxautosave.log 2>&1 & )
		fi
	fi
else
	#
	# Otherwise, announce that mxautosave was not started.
	#

	DATE=`date +'%b %d %H:%M:%S'`

	#echo \
#"${DATE} *** mxautosave was not started, since ${MXDIR}/etc/mxautosave.dat is empty or does not exist. ***" >> ${MXDIR}/log/mxautosave.log

	#
	# Make sure that mxautosave.pid does not exist.
	#
	if [ -f ${MXDIR}/run/mxautosave.pid ]; then
		rm -f ${MXDIR}/run/mxautosave.pid
	fi
fi

