#! /bin/sh

if [ x$MXDIR = x ]; then
	MXDIR=/opt/mx
fi
if [ x$MXPORT = x ]; then
	MXPORT=9727
fi

#
# If we need to customize the environment of the MX server before
# we start it, then we need to provide an mxserver.custom script
# to do the customizations.
#

MXSERVER_CUSTOM_FILE=${MXDIR}/etc/mxserver.custom

if [ -f ${MXSERVER_CUSTOM_FILE} ]; then
	. ${MXSERVER_CUSTOM_FILE}
fi

if [ x$LD_LIBRARY_PATH = x ]; then
	LD_LIBRARY_PATH=${MXDIR}/lib
else
	LD_LIBRARY_PATH="${MXDIR}/lib:${LD_LIBRARY_PATH}"
fi

if [ x$DYLD_LIBRARY_PATH = x ]; then
	DYLD_LIBRARY_PATH=${MXDIR}/lib
else
	DYLD_LIBRARY_PATH="${MXDIR}/lib:${DYLD_LIBRARY_PATH}"
fi

if [ x$SHLIB_PATH = x ]; then
	SHLIB_PATH=${MXDIR}/lib
else
	SHLIB_PATH="${MXDIR}/lib:${SHLIB_PATH}"
fi

export MXDIR LD_LIBRARY_PATH DYLD_LIBRARY_PATH SHLIB_PATH

MXSERVER=${MXDIR}/sbin/mxserver

if [ -x $MXSERVER ]; then
	cd ${MXDIR}/run

	echo $$ > ${MXDIR}/run/mxserver.pid

	exec $MXSERVER -p $MXPORT -f ${MXDIR}/etc/mxserver.dat \
		-C ${MXDIR}/etc/mxserver.acl $* 
fi

