#
# Configure the sections below that apply to your MX target platform
# and EPICS architecture.
#
# The MX architectures currently supported by the 'epics' module include:
#
#   cygwin, linux, macosx, solaris, solaris-gcc, win32
#

#--------------------------------------------------------------------------

# Cygwin configuration

ifeq ($(MX_ARCH),cygwin)

EPICS_ARCH	= cygwin-x86

EPICS_TOP	= /opt/epics
#EPICS_TOP	= /cygdrive/c/opt/epics/R3.14.10

EPICS_INCLUDES	= -Wno-shadow -I$(EPICS_TOP)/base/include \
			-I$(EPICS_TOP)/base/include/os/cygwin32
EPICS_LIB_DIRS	= -L$(EPICS_TOP)/base/lib/$(EPICS_ARCH)
EPICS_LIBRARIES	= -lca -lCom

endif

#--------------------------------------------------------------------------

# Linux configuration

ifeq ($(MX_ARCH),linux)

#EPICS_ARCH	= linux-x86_64		# For EPICS 3.14
EPICS_ARCH	= linux-x86		# For EPICS 3.14
#EPICS_ARCH	= linux-ppc		# For EPICS 3.14
#EPICS_ARCH	= linux-x86-debug	# For EPICS 3.14
#EPICS_ARCH	= linux-x86_64-debug	# For EPICS 3.14

MX_EPICS_CFLAGS = $(CFLAGS) -Wno-strict-prototypes -Wno-cast-qual -Wno-shadow

# For sites that have built EPICS from source, use the following definitions.

EPICS_TOP	= /opt/epics
#EPICS_TOP	= /opt/EPICS
#EPICS_TOP	= /mnt/epics
#EPICS_TOP	= /usr/local/epics
#EPICS_TOP	= /home/lavender/local/opt/epics
#EPICS_TOP	= /home1/daly/epics

#EPICS_INCLUDES	= -Wno-shadow -I$(EPICS_TOP)/base/include \
#			-I$(EPICS_TOP)/base/include/os/Linux
#EPICS_LIB_DIRS	= -L$(EPICS_TOP)/base/lib/$(EPICS_ARCH)
#EPICS_LIBRARIES = -lca -lCom

# If you are using the NSLS-II EPICS Debian packages, then use the following
# definitions.
#
# The NSLS-II Debian packages can be found at http://epics.nsls2.bnl.gov/debian/
#     

EPICS_INCLUDES  = -Wno-shadow -I/usr/lib/epics/include \
			-I/usr/lib/epics/include/os/Linux
EPICS_LIB_DIRS  = -L/usr/lib/epics/lib/$(EPICS_ARCH)
EPICS_LIBRARIES = -lca -lCom

# If you are using IIT's EPICS Debian packages, then use the following
# definitions.
#
# IIT's Debian and Ubuntu packages can be found at http://debian-xray.iit.edu/
#     

#EPICS_INCLUDES  = -Wno-shadow -I/usr/include/epics \
#			-I/usr/include/epics/os/Linux
#EPICS_LIB_DIRS  = 
#EPICS_LIBRARIES = -lca -lCom

endif

#--------------------------------------------------------------------------

# MacOS X configuration

ifeq ($(MX_ARCH),macosx)

EPICS_ARCH	= darwin-x86
#EPICS_ARCH	= darwin-ppc

MX_EPICS_CFLAGS = $(CFLAGS)

EPICS_TOP	= /opt/epics

EPICS_INCLUDES	= -I$(EPICS_TOP)/base/include \
			-I$(EPICS_TOP)/base/include/os/Darwin
EPICS_LIB_DIRS	= -L$(EPICS_TOP)/base/lib/$(EPICS_ARCH)
EPICS_LIBRARIES = -lca -lCom

endif

#--------------------------------------------------------------------------

# Solaris configuration

ifeq ($(MX_ARCH),solaris)

EPICS_ARCH	= solaris-sparc
#EPICS_ARCH	= solaris-x86

#EPICS_TOP	= /opt/epics
#EPICS_TOP	= /usr/local/epics
EPICS_TOP	= /filer/Data/epicsUIC

EPICS_INCLUDES	= -I$(EPICS_TOP)/base/include \
			-I$(EPICS_TOP)/base/include/os/solaris
EPICS_LIB_DIRS	= -L$(EPICS_TOP)/base/lib/$(EPICS_ARCH)
EPICS_LIBRARIES = -lca -lCom

endif

#--------------------------------------------------------------------------

# Solaris GCC configuration

ifeq ($(MX_ARCH),solaris-gcc)

EPICS_ARCH	= solaris-sparc-gnu
#EPICS_ARCH	= solaris-x86-gnu

EPICS_TOP	= /opt/epics

EPICS_INCLUDES	= -I$(EPICS_TOP)/base/include \
			-I$(EPICS_TOP)/base/include/os/solaris
EPICS_LIB_DIRS	= -L$(EPICS_TOP)/base/lib/$(EPICS_ARCH)
EPICS_LIBRARIES = -lca -lCom

endif

#--------------------------------------------------------------------------

# Win32 configuration

ifeq ($(MX_ARCH),win32)

#EPICS_ARCH	= win32-x86
EPICS_ARCH	= windows-x64

MX_EPICS_CFLAGS = $(CFLAGS)

EPICS_BASE	= c:\\opt\\epics\\base-3.14.12.2
#EPICS_BASE	= c:\\opt\\epics\\base-3-14-11
#EPICS_BASE	= d:\\opt\\epics\\base-3.14.12

EPICS_INCLUDES	= -I$(EPICS_BASE)\\include \
			-I$(EPICS_BASE)\\include\\os\\WIN32
EPICS_LIBS	= $(EPICS_BASE)\\lib\\$(EPICS_ARCH)\\ca.lib \
			$(EPICS_BASE)\\lib\\$(EPICS_ARCH)\\Com.lib

endif

#--------------------------------------------------------------------------

