#
# tools/Makefile.rtems
#

all:  strlcpy.o strlcat.o xdr_hyper.o

include ../libMx/Makehead.rtems

mx_clean:
	-rm *.o

strlcpy.o: generic/src/strlcpy.c
	$(CC) -c $(CFLAGS) -D__MX_LIBRARY__ generic/src/strlcpy.c

strlcat.o: generic/src/strlcat.c
	$(CC) -c $(CFLAGS) -D__MX_LIBRARY__ generic/src/strlcat.c

xdr_hyper.o: xdr/src/xdr_hyper.c xdr/src/xdr.h xdr/src/xdr_hyper.h
	$(CC) -c $(CFLAGS) -I../libMx -DOS_RTEMS \
		-D__MX_LIBRARY__ xdr/src/xdr_hyper.c

