#
# tools/Makefile.rtems
#

all:  strlcpy.o strlcat.o

include ../libMx/Makehead.rtems

mx_clean:
	-rm *.o

strlcpy.o: generic/src/strlcpy.c
	$(CC) -c $(CFLAGS) -D__MX_LIBRARY__ generic/src/strlcpy.c

strlcat.o: generic/src/strlcat.c
	$(CC) -c $(CFLAGS) -D__MX_LIBRARY__ generic/src/strlcat.c

