#
# If you are building the software for National Instruments DAQmx Base
# rather than DAQmx, then set USE_DAQMX_BASE to TRUE below.  Otherwise,
# set it to FALSE.
#

USE_DAQMX_BASE = FALSE

USE_64_BITS = TRUE

ifeq ($(MX_ARCH),linux)
	NI_DAQMX_ANSI_C_DIR = /usr/local/natinst/nidaqmxbase

	CFLAGS += -I$(NI_DAQMX_ANSI_C_DIR)/include
endif

ifeq ($(MX_ARCH),win32)

	ifeq ($(USE_DAQMX_BASE),TRUE)
		NI_DAQMX_ANSI_C_DIR = c:\\progra~1\\nation~1\\ni-daq~1
		NI_DAQMX_LIBRARY = $(NI_DAQMX_ANSI_C_DIR)\\lib\\nidaqmxbase.lib
	else
		NI_DAQMX_ANSI_C_DIR = \
		    c:\\progra~2\\nation~1\\Shared\\ExternalCompilerSupport\\C

		##NI_DAQMX_ANSI_C_DIR = \
		##    c:\\progra~1\\nation~1\\Shared\\ExternalCompilerSupport\\C

		##NI_DAQMX_ANSI_C_DIR = \
		##    d:\\progra~1\\nation~1\\Shared\\ExternalCompilerSupport\\C

		ifeq ($(USE_64_BITS),TRUE)
			NI_DAQMX_LIBRARY = \
			    $(NI_DAQMX_ANSI_C_DIR)\\lib64\\msvc\\NIDAQmx.lib
		else
			NI_DAQMX_LIBRARY = \
			    $(NI_DAQMX_ANSI_C_DIR)\\lib32\\msvc\\NIDAQmx.lib
		endif
	endif

	CFLAGS += -DWIN32
	CFLAGS += -I$(NI_DAQMX_ANSI_C_DIR)\\include
endif

ifeq ($(USE_DAQMX_BASE),TRUE)
	CFLAGS += -DUSE_DAQMX_BASE
endif

